### ISSUE TITLE
Create logical data models

### ISSUE THREAD

**Issue by costateixeira** [IHE/pharm-meow#14]
Independent from FHIR.

Collect logical models from relevant specifications.
Create and document the data model.

**Comment by rlindstrm** [comment]
The new ones are marked with NEW in the specification. http://build.fhir.org/ig/IHE/pharm-meow/branches/main/artifacts.html#1 
Shall we make it into one tree or keep separately?

**Comment by rlindstrm** [comment]
From 31.07.2023 meeting:
[Medication Overview model](http://build.fhir.org/ig/IHE/pharm-meow/branches/main/StructureDefinition-MedicationOverview.html)

An overview may include verified and unverified treatment lines.
**Verification information** per overview and per treatment line. Seems to support different use cases, and seems ok for now.
**Comments** can reference a treatment line, treatment, or full overview.

[Medication Treament Line model](http://build.fhir.org/ig/IHE/pharm-meow/branches/main/StructureDefinition-MedicationTreatmentLine.html) 

**Treatment groups**  - can we have a medication that belongs to more than one group. Theoretically yes, but not sure if implemented like this in real world. However, 0..* is probably safer to go with.

**Indication** - text added, because we might not always have the code (esp for patient statements).

**UsageInstructions** - use FHIR model. Better name might be needed, because instructions refer to a request/prescription, but patient statements are just stating a fact.

**Missing one actor**: 
- Makes clinical decision _Author_
- Writes down _Reporter_
- Checks the full overview  _Verifier_ 
Added the missing role. "Author", however is not the best term for this role, and would be nice to have a better name for it.

**RelatedWhatnots**
RelatedPrescriptions and RelatedStatements OK. Using RelatedRequest instead of RelatedPrescription. Must keep in sync with MPD.
RelatedDispensations for dispensations that are not following prescriptions. Would be relevant for OTC drugs. Dispensation before prescription allowed in Switzerland, so technically this should be allowed but not encouraged.

[Medication Treatment model](http://build.fhir.org/ig/IHE/pharm-meow/branches/main/StructureDefinition-MedicationTreatment.html)
This represents a group of treatment lines, where treatments are strongly connected to eachother and should always be treated as a set.
Added Indication.
Should it have an Identifier?
Nobody remembers what Advice is.
Comment is also on the overview level, and can reference the group. Is it needed on this level?
We’ll discuss this model again when @costateixeira is back.

**Comment by rlindstrm** [comment]
#12 is the [Medication ](http://build.fhir.org/ig/IHE/pharm-meow/branches/main/StructureDefinition-MedicinalProduct.html)logical model discussion.
